# Generated by Django 4.0.2 on 2022-02-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=30)),
                ('birth', models.IntegerField(default=2000)),
                ('birth_day', models.DateField()),
                ('college', models.CharField(max_length=60)),
                ('univerity', models.CharField(max_length=60)),
                ('im1', models.CharField(max_length=100)),
                ('im2', models.CharField(max_length=100)),
                ('im3', models.CharField(max_length=100)),
                ('html', models.IntegerField(default=100)),
                ('django', models.IntegerField(default=70)),
                ('php', models.IntegerField(default=50)),
                ('css', models.IntegerField(default=70)),
                ('bootstrap', models.IntegerField(default=20)),
                ('python', models.IntegerField(default=80)),
                ('cshap', models.IntegerField(default=40)),
                ('kotlin', models.IntegerField(default=60)),
                ('c_and_cpp', models.IntegerField(default=60)),
            ],
        ),
    ]
