# Generated by Django 4.0.2 on 2022-02-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='me',
            old_name='last_name',
            new_name='namet',
        ),
    ]
