# Generated by Django 4.0.2 on 2022-02-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_last_name_me_namet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='me',
            old_name='namet',
            new_name='last_name',
        ),
    ]
