# Generated by Django 4.0.2 on 2022-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_namet_me_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='im4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
