# Generated by Django 4.0.2 on 2022-02-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_me_im4'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='facebook',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='linkedin',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='telegram',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='whatsapp',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='im4',
            field=models.CharField(default='freelance', max_length=100, null=True),
        ),
    ]
