# Generated by Django 4.0.2 on 2022-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_me_facebook_me_linkedin_me_telegram_me_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='about',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
