# Generated by Django 4.0.2 on 2022-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_me_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='number1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='number2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
