# Generated by Django 4.0.2 on 2022-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_me_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='js',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
